# Generated by Django 5.0.4 on 2024-04-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='staticfiles/assets/img/avatar.jpg', null=True, upload_to='profile_pictures/'),
        ),
    ]
