# Generated by Django 5.0.4 on 2024-04-27 06:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_date_post_publication_date_post_tags_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a 10 digit without any symbols, character, STD pin!', regex='^[6-9][0-9]{9}$')])),
                ('message', models.CharField(max_length=500)),
            ],
        ),
    ]
