# Generated by Django 5.0.4 on 2024-04-27 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_contact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='blog_post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comment_text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='publication_date',
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, max_length=460, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
