# Generated by Django 5.0.4 on 2024-04-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_blogpostx_author_remove_blogpostx_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
