# Generated by Django 5.0.4 on 2024-04-30 18:30

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_commentreply_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='preview',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
