# Generated by Django 5.0.4 on 2024-04-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_weatherdata_conditions_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weatherdata',
            old_name='conditions_icon',
            new_name='condition_icon',
        ),
    ]
